### ISSUE TITLE
[Bug] /command 所提供的網址後面多了反斜線

### ISSUE THREAD

**Issue by EvanHsieh0415** [AlexCai2019/Cartoland#4]
![圖片](https://user-images.githubusercontent.com/74277414/222315611-9b0a58ad-f55c-49ba-a54a-08dae428fb19.png)
應為`https://minecraft.fandom.com/zh/wiki/命令/datapack?variant=zh-tw`
不影響使用，但可能導致語言參數錯誤

**Comment by AlexCai2019** [comment]
經查沒有反斜線，不過確實有一條正斜線，日後更新時再一併處理。
